app/__init__.py
from flask import Flask

app = Flask(__name__)
app.config.from_object('config.Config')

from app.main.controller import main as main

app.register_blueprint(main)

app/main/controller.py
from flask import render_template, request, Blueprint
from . import linkedListService

main = Blueprint('main', __name__, url_prefix='/')

@main.route('/', methods=['DELETE', 'GET', 'POST'])
def index():
    boxes = linkedListService.dataToLinkedList()
    query = request.args.get('search', '')
    sort = request.args.get('sort', '')
    abc = request.args.get('abc', '')

    if sort == '':
        sort = 'time'
        abc = '0'


    if request.method == 'DELETE':
        data = request.get_json('id')
        linkedListService.deleteBoxById(boxes, (int)(data['id']))

    if query == '':
        that = linkedListService.getSortedBoxes(boxes, sort, abc)
    else:
        that = linkedListService.findByStudentNumber(boxes, query)
    
    return render_template('index.html', boxes=that, search=query, abc=abc, sort=sort)


@main.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'POST':
        boxes = linkedListService.dataToLinkedList()
        name = request.form['name']
        studentNumber = request.form['studentNumber']
        content = request.form['content']

        if name == '' or studentNumber == '':
            return '값을 입력해 주세요.'
        linkedListService.setBox(boxes, name, studentNumber, content)

    return render_template('register.html')

app/main/views.py
from flask import Flask, redirect, render_template, request, url_for, Blueprint
from . import works

main = Blueprint('main', __name__, url_prefix='/')

@main.route('/', methods=['DELETE', 'GET'])
def index():
    boxes = works.dataToLinkedList()
    query = request.args.get('search', '')

    
    if request.method == 'DELETE':
        data = request.get_json('id')
        works.deleteBoxById(boxes, (int)(data['id']))


    if query == '':
        that = works.getBoxes(boxes)
        that.reverse()
    else:
        that = works.findByStudentNumber(boxes, query)
    
    return render_template('test.html', boxes=that, search=query) #최태영거완성되면수정

@main.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'POST':
        boxes = works.dataToLinkedList()
        name = request.form['name']
        studentNumber = request.form['studentNumber']

        if name == '' or studentNumber == '':
            return '값을 입력해 주세요.'
        works.setBox(boxes, name, studentNumber)

    return render_template('registerTest.html')

app/templates/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <title>가져가!!!</title>
</head>
<body>
    <button class="btn2"><a href="{{ url_for('main.register') }}">등록</a></button>
    <h1><a href="{{ url_for('main.index') }}">가져가!!!</a></h1>
    
    <center>
    <div class="search">
        <input id="search" type="text" value="{{ search }}" placeholder="학번을 입력해 택배를 조회하세요">
        <button class="btn" onclick="javascript:moveUrl()">검색</button>
    </div>

    {% if search == '' %}
    <div id="sortBox">
        <select id="sort" name="sort">
            <option value="time">시간순</option>
            <option value="studentNumber">학번순</option>
            <option value="name">이름순</option>
        </select>
        <button type="button" onclick="javascript:setSortImage()" value="" id="abc" name="abc">
            <img id="sortImage" src="">
        </button>
        <button class="btn3" onclick="javascript:moveUrl()">적용</button>
    </div>
    {% endif %}
    
    </center>
    <div class="list">
    <ul>
        {% for box in boxes %}
        <center>
        <li>
            <h3 style="display: inline">{{ box.studentNumber }}</h3>
            <h3 style="display: inline">{{ box.name }}</h3><br>
            <p style="display: inline">{{ box.content }}</p>
            <p style="display: inline">{{ box.date }}</p>
            <p style="display: inline">{{ box.time }}</p>
            {% if search != '' %}
            <button onclick="javascript:deleteBox('{{ box.id }}')">삭제</button>
            {% endif %}
        </li>
        {% endfor %}
    </center>
    </ul>
</div>
</body>
<script>
    const sort = document.getElementById("sort");
    const abc = document.getElementById("abc");
    const image = document.getElementById("sortImage");
    const searchContent = document.getElementById("search");

    window.onload = function() {
        console.log('set 실행됨')

        sort.value = '{{ sort }}';
        abc.value = '{{ abc }}';
        
        if (abc.value == '1') {
            image.src = "{{ url_for('static', filename='images/narim.png') }}";
        }
        else if (abc.value == '0'){
            image.src = "{{ url_for('static', filename='images/oreum.png') }}";
        }
    }
    function moveUrl() {
        window.location.href = "{{ url_for('main.index') }}"+"?search="+searchContent.value+"&sort="+sort.value+"&abc="+abc.value;
    }
    function deleteBox(id) {
        const data = {
            id,
        }
        $.ajax({
            type: 'DELETE',
            url: "{{ url_for('main.index') }}",
            //dataType: 'json',
            data: JSON.stringify(data),
            error: function(request,status,error){
                console.log("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
            }
        })

        window.location.reload()
    }
    function setSortImage() {
        if (abc.value == '1') {
            abc.value = '0';
            image.src = "{{ url_for('static', filename='images/oreum.png') }}";
        }
        else if (abc.value == '0'){
            abc.value = '1';
            image.src = "{{ url_for('static', filename='images/narim.png') }}";
        }
    }
</script>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/register.css') }}">
    <title>가져가!!!</title>
</head>
<body>
    <h1><a href="{{ url_for('main.index') }}">가져가!!!</a></h1>
    <p>등록할 택배의 정보를 입력해주세요.</p>
    <form action="" method="post">
        <input name="name" placeholder="이름">
        <input name="studentNumber" placeholder="학번">
        <input name="content" placeholder="택배 물품"><br><br>
        <button type="submit">등록</button>
    </form>
</body>
</html>

app/templates/registerTest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>가져가!!!</title>
</head>
<body>
    <form action="" method="post">
        <input type="text" name="name">
        <input type="text" name="studentNumber">
        <input type="submit">
    </form>
</body>
</html>

app/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <title>가져가!!!</title>
</head>
<body>
    <button><a href="{{ url_for('main.register') }}">등록</a></button>
    <input id="search" type="text" value="{{ search }}" placeholder="학번을 입력하세요">
    <button type="button" onclick="javascript:search()">검색</button>
    <ul>
        {% for box in boxes %}
        <li>
            <p>{{ box.name }}</p>
            <p>{{ box.studentNumber }}</p>
            <p>{{ box.date }}</p>
            <p>{{ box.time }}</p>
            <p>{{ box.id }}</p>
            {% if search != '' %}
            <button onclick="javascript:deleteBox('{{ box.id }}')">삭제</button>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
</body>
<script>
    function search() {
        var search = document.getElementById("search").value;
        window.location.href = "{{ url_for('main.index') }}"+"?search="+search;
    }

    function deleteBox(id) {
        const data = {
            id,
        }
        $.ajax({
            type: 'DELETE',
            url: "{{ url_for('main.index') }}",
            dataType: 'json',
            data: JSON.stringify(data),
            error: function(request,status,error){
                console.log("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
            }
        })

        window.location.reload()
    }
</script>
</html>